itblog/itblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import main.views
import main.login_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main.views.home, name='home'),
    url(r'^subject$', main.views.subjects, name='subjects'),
    url(r'^about$', main.views.about, name='about'),
    url(r'^links$', main.views.links, name='links'),

    url(r'^accounts/login/$', main.login_views.login_user, name='login'),
    url(r'^login$', main.login_views.login_user, name='login'),
    url(r'^logout', main.login_views.logout_user, name='logout'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

articles = [
    url(r'^(?P<page_type>tags|subjects|search|recent)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)$', main.views.main, name='main'),
    url(r'^(?P<page_type>tags|subjects|search|recent)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)/(?P<page>\d+)/(?P<delta>\d+)$', main.views.main, name='main'),
    url(r'^blog/(?P<article_id>\d+)$', main.views.blog, name='blog'),
]

article = [
    url(r'^add$', main.views.add_article, name='addarticle'),
    url(r'^edit/(?P<article_id>\d+)$', main.views.edit_article, name='editarticle'),
    url(r'^preview/(?P<article_id>\d+)$', main.views.preview_article, name='previewarticle'),
]

comments = [
    url(r'^answer_to/(?P<comment_id>\d+)$', main.views.comment_dialog, name='commentdialog'),
    url(r'^edit/(?P<comment_id>\d+)$', main.views.edit_comment, name='editcomment'),
]

urlpatterns += [
    url(r'^articles/', include(articles)),
    url(r'^article/', include(article)),
    url(r'^comments/', include(comments)),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

itblog/tasks/urls.py
from django.conf.urls import include, url

import tasks.views


urlpatterns = [
    url(r'^(?P<page_type>tags|subjects|search|all)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)$', tasks.views.main, name='tasks'),
    url(r'^(?P<page_type>tags|subjects|search|all)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)/(?P<page>\d+)/(?P<delta>\d+)$', tasks.views.main, name='tasks'),
    url(r'^subjects$', tasks.views.subjects, name='tasksubjects'),
    url(r'^(?P<task_id>\d+)$', tasks.views.task, name='task'),
    url(r'^add$', tasks.views.add_task, name='addtask'),
    url(r'^edit/(?P<task_id>\d+)$', tasks.views.edit_task, name='edittask'),
    url(r'^solution/edit/(?P<solution_id>\d+)$', tasks.views.edit_solution, name='editsolution'),
    url(r'^comment/(?P<solution_id>\d+)$', tasks.views.add_solution_comment, name='addsolutioncomment'),
    url(r'^comment/(?P<comment_id>\d+)/edit$', tasks.views.edit_solution_comment, name='editsolutioncomment'),
]

itblog/main/models.py
from django.db import models
from django.contrib.auth.models import User

import os

def _get_upload_path(instance, filename):
    return filename
#     return os.path.join(instance.article.id, filename)


class Subject(models.Model):
    
    name = models.CharField(max_length=40, unique=True)
    parent_subject = models.ForeignKey('self', blank=True, null=True, verbose_name='Parent subject')
    
    def __unicode__(self):
        return self.name


class Tag(models.Model):
    
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.SET(None))
    amount = models.PositiveIntegerField(default=0)
    
    def __unicode__(self):
        return self.name


class Article(models.Model):
    
    author = models.ForeignKey(User, on_delete=models.SET(0))
    title = models.CharField(max_length=100, unique=True)
    body = models.TextField()
    subject = models.ForeignKey(Subject, on_delete=models.SET(0))
    date = models.DateTimeField(auto_now=True)
#     tags = models.CharField(max_length=200)
    mtags = models.ManyToManyField(Tag)
    is_published = models.BooleanField(default=False)
    
    @property
    def tags_list(self):
        return self.tags.split(',')
    
    def is_in_favorites(self, user):
        return True if Favorite.objects.filter(article_id=self.id, owner=user) else False


class ArticleImage(models.Model):
    
    article = models.ForeignKey(Article, null=True, blank=True)
    image = models.ImageField(upload_to=_get_upload_path)


class UsefulLink(models.Model):
    
    url = models.URLField(max_length=300)
    description = models.CharField(max_length=100, blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.SET(0))
    
    def __unicode__(self):
        return self.url


class Comment(models.Model):
    
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Name')
    author = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET('Undefined'))
    body = models.TextField(verbose_name='Comment')
    article = models.ForeignKey(Article)
    date = models.DateTimeField(auto_now=True)
    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='Parent comment')


class Favorite(models.Model):
    
    class Meta:
        unique_together = ('owner', 'article')
    
    owner = models.ForeignKey(User)
    comment = models.TextField(verbose_name='Comment', blank=True, null=True)
    article = models.ForeignKey(Article)

itblog/main/views.py
#coding: utf-8 
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.datastructures import MultiValueDict
from django import forms

from .forms import *
from .models import *
from .utils import get_query, get_pagination_info, \
                  send_mail, refresh_captcha, get_neighbors


import json

def home(request):
    context_dict = {}
    context_dict['recent_articles'] = get_recent_articles()
    context_dict['tags'] = Tag.objects.all().filter(article__is_published=True)\
                                .distinct().order_by('name')
    context_dict['list'] = get_subjects_tree()
    return render(request, 'main/home.html', context_dict)

@login_required
def subjects(request):
    """
    Is responsible for 'Subjects manager'
    """
    result = []
    for subject in Subject.objects.filter(parent_subject=None):
        result.append({
                'parent' : subject,
                'children' : Subject.objects.filter(parent_subject=subject)})
    
    if request.method == 'POST':
        # add subject
        if not request.POST.get('item_id'):
            form = SubjectForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('subjects')
        
        # edit subject
        elif request.POST.get('edit_request'):
            subject = Subject.objects.get(pk=int(request.POST['item_id']))
            form = SubjectForm(instance=subject)
            return render(request,
                                      'main/forms/rowform.html',
                                      {
                                       'form' : form ,
                                       'item_id' : subject.id
                                       })
        
        elif request.POST.get('edit_submit'):
            form = SubjectForm(request.POST,
                               instance=Subject.objects.get(
                                                    pk=request.POST['item_id']))
            if form.is_valid():
                form.save()
                return HttpResponse("")
            else:
                return render(request,
                                          'main/forms/rowform.html',
                                          {
                                           'form' : form ,
                                           'item_id' : request.POST['item_id']
                                           })
        
        # delete subject
        elif request.POST.get('delete_request'): 
            subject = Subject.objects.get(pk=int(request.POST['item_id']))
            subject.delete()
            return HttpResponse('')
    # empty form
    else:
        form = SubjectForm()
    return render(request, 'main/base/subjects.html',
                              {
                               'page_title' : 'Articles subjects',
                               'result' : result,
                               'form' : form
                               })


def main(request, page_type, item_name, page=1, delta=10, **kwargs):
    
    context_dict = {}
    context_dict['recent_articles'] = get_recent_articles()
    context_dict['tags'] = Tag.objects.all().filter(article__is_published=True)\
                                .distinct().order_by('name')
    context_dict['list'] = get_subjects_tree()
    context_dict['page_type'] = page_type
    context_dict['item_name'] = item_name
    
    # subjects_results, tag_results, search_results, recent_results
    return globals()[page_type + '_results'](request, context_dict,
                                             item_name=item_name,
                                             page=int(page),
                                             delta=int(delta))


def blog(request, article_id=0):
    
    context_dict = {}
    context_dict['recent_articles'] = get_recent_articles()
    context_dict['tags'] = Tag.objects.all().filter(article__is_published=True)\
                                .distinct().order_by('name')
    context_dict['list'] = get_subjects_tree()
    context_dict['query'] = request.GET.get('q', '')

    if not int(article_id):
        return redirect('main', 'recent', 0)
 
    try:
        article = Article.objects.get(pk=int(article_id), is_published=True)
        articles = list(Article.objects.filter(subject=article.subject,
                                           is_published=True).order_by('pk'))
         
        context_dict['previous'], context_dict['next'] = get_neighbors(article,
                                                                       articles)
    except Article.DoesNotExist:
        return redirect('main', 'recent', 0)

    context_dict['article'] = article
        
    if request.user.is_authenticated():
        form = CommentForm(initial={'author': request.user,
                                    'article':article,
                                    'parent_comment' : None})
        form.fields['name'].widget = forms.HiddenInput()
    else:
        form = CommentForm(initial={'article':article,
                                    'parent_comment' : None})
     
    if request.is_ajax() and 'refresh_captcha' in request.GET:
        return refresh_captcha()
     
    if request.method == 'POST':
        if request.POST.get('add_request'):
            if request.POST['type'] == 'favorites':
                Favorite.objects.create(owner=request.user, article=article)
        if request.POST.get('delete_request'):
            if request.POST['type'] == 'comment':
                comment = Comment.objects.get(pk=int(request.POST['item_id']))
                comment.delete()
            elif request.POST['type'] == 'article':
                article = Article.objects.get(pk=int(request.POST['item_id']))
                 
                for tag in article.mtags.all():
                    tag.amount -= 1
                    tag.save()
                 
                for img in ArticleImage.objects.filter(article=article):
                    _delete_image(img.id)
                 
                article.delete()
                return HttpResponse('Article was successfully deleted.')
            elif request.POST['type'] == 'favorite':
                favorite = Favorite.objects.get(article_id=article_id)
                favorite.delete()
        else:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save()
                 
                message_subject = 'New comment for your article \"%s\"' \
                                                                % article.title
                message_body = "User %s has added a new comment to your post." +\
                "\nGo here and view it:\nwww.it-recipes.com%s" 
                message_body = message_body % (comment.author, request.get_full_path())
                 
                send_mail(article.author.email, message_subject, message_body)
                 
                return redirect('blog', article.id)
            else:
                if request.user.is_authenticated():
                    form.fields['name'].widget = forms.HiddenInput()
     
    context_dict['form'] = form
    context_dict['comments'] = get_comments_tree(article_id)
    
    return render(request, 'main/blog/blog.html', context_dict)


def edit_comment(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    form = CommentForm(instance=comment)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('blog', comment.article.id)
    if request.user.is_authenticated():
        form.fields['name'].widget = forms.HiddenInput()
    return render(request, 'main/blog/editcomment.html',
                    {
                     'comment' : comment,
                     'form' : form,
                     'cancel_link' : reverse('blog', args=(comment.article.id,))
                     })


def comment_dialog(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    if request.user.is_authenticated():
        form = CommentForm(initial={'author': request.user,
                                    'article':comment.article,
                                    'parent_comment' : comment})
    else:
        form = CommentForm(initial={'article':comment.article,
                                    'parent_comment' : comment})
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog', comment.article.id)
    if request.user.is_authenticated():
        form.fields['name'].widget = forms.HiddenInput()
    return render(request, 'main/blog/commentdialog.html',
                    {
                     'comment_dialog' : get_comment_dialog(comment_id),
                     'form' : form,
                     'cancel_link' : reverse('blog', args=(comment.article.id,))
                     })


def tags_results(request, context_dict, **kwargs):
    tag_name = str(kwargs.get('item_name'))
    p = int(kwargs.get('page'))
    delta = int(kwargs.get('delta'))
    try:
        articles = Tag.objects.get(name=tag_name).article_set\
                                                    .filter(is_published=True)\
                                                    .select_related('subject')
    except Tag.DoesNotExist:
        articles = []
                                                

itblog/main/templates/main/forms/articleform.html
<form method="POST" id="id_article_form">{% csrf_token %}
	<div class="control-group">
    	<div class="controls">
			<div style="color:red">{{ form.non_field_errors }}</div>
		</div>
	</div>

	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{{ field.label }} {{ field.help_text }}
		<div class="controls">
			{{ field }}
			<span class="help">{{ field.errors }}</span>
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
		{{ field }}
	{% endfor %}
	<input type="hidden" id="id_submit_type" name="submit_type">
	<input type="hidden" id="id_article_images" name="article_images">

    	<div class="controls">
    		<a href="#" class="btn btn-success" onclick="$('#id_submit_type').val('publish'); $('#id_is_published').val('True'); $('#id_article_form').submit();">Publish article</a>
    		<a href="#" class="btn btn-info" onclick="$('#id_submit_type').val('draft'); $('#id_article_form').submit()">Save in drafts</a>
    		<a href="#" class="btn" onclick="$('#id_submit_type').val('preview'); $('#id_article_form').submit()">Preview</a>
			{% if article.id and article.is_published %}
				<a href="{% url 'blog' article.id %}" class="btn">Cancel</a>
			{% elif not article.is_published %}
				<a href="{% url 'dash' 'drafts' 0 %}" class="btn">Cancel</a>
			{% else %}
				<a href="{% url 'blog' 0 %}" class="btn">Cancel</a>
			{% endif %}
		</div>
	</div>
</form>

{% if images %}
	<div class="alert alert-info" style="margin-left:70px;">
		<h3>Uploaded images</h3>
		{% for file in images %}
			<div style = "margin:10px" id="image_div_{{ file.id }}">
				<img src='{{ file.image.url }}' style="width:50px;"/>&nbsp;&nbsp;{{ file.image.name }} 
				<a class="btn btn-mini" onclick="remove_image(event, {{ file.id }})"><icon class="icon-minus"></i></a><br/>
			</div>
		{% endfor %}
	</div>
{% endif %}

<div id="form_div" class="alert alert-info" style="margin-left:70px;">
	<h3>Add new images</h3>
	<form enctype="multipart/form-data" method="POST" id="image_form">
		<input id="id_image" type="file" accept=".jpg,.png,.gif" name="image">
		<a class="btn" onclick="upload_image(event)">Add image</a>
		<img id="loading_info" src="{{ STATIC_URL }}img/loading_big.gif" class="hidden" width=30/>
	</form>
</div>

<div>
<!-- <input type="text" id="log"> -->
<script>
// $("#log").bind("keyup",function(e){
    // alert(this.value + e.keyCode)
// });

$(document).ready(function() {
	$("input").each(function() {
		if (typeof $(this).attr('id') == 'undefined') {
			$(this).attr('data-provide', 'typeahead').attr('data-source', '[' + '{{ tags }}'.replace(/&#39;/g, '\"') + ']')
			// $(this).tagsinput({
			    // confirmKeys: [32]
			    // });
		}
	})
})
</script>

itblog/main/templates/main/forms/commentform.html
<script>
	window.onload = function() {
		CKEDITOR.replace('body', {
			language : 'en',
			toolbar : 'Basic',
			uiColor : '#D7E4F0',
			removePlugins : 'resize',
			width : 542,
		});
	};
</script>
<form method="POST">{% csrf_token %}
	<div class="control-group">
    	<div class="controls">
			<div style="color:red">{{ form.non_field_errors }}</div>
		</div>
	</div>

	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{{ field.label }}
		<div class="controls">
			{{ field }}
			{% if field.name == 'captcha' %}
				<a class="btn btn-small btn-refresh" onclick="refresh_captcha()"><i class="icon-refresh"></i> Refresh</a>
			{% endif %}
			<span class="help">{{ field.errors }}</span>
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
		{{ field }}
	{% endfor %}
	<div class="control-group">
    	<div class="controls">
    		<input type='submit' class="btn btn-success" value = "Add comment"/>
			<a href="{{ cancel_link }}" class="btn">Cancel</a>
		</div>
	</div>
</form>

itblog/main/templates/main/forms/defaultform.html
<form method="POST">{% csrf_token %}
	
	<div class="control-group">
    	<div class="controls">
			<div style="color:red">{{ form.non_field_errors }}</div>
		</div>
	</div>

	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{{ field.label }}
		<div class="controls">
			{{ field }}
			<span class="help">{{ field.errors }}</span>
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
		{{ field }}
	{% endfor %}
	
	<div class="control-group">
    	<div class="controls">
			<input type='submit' class="btn btn-success" value = "{{ submit_title }}"/>
			<a href="{{ request.get_full_path }}" class="btn">{{ cancel_title }}</a>
		</div>
	</div>
</form>

itblog/main/templates/main/forms/loginform.html
<form method="POST" class="form-horizontal">{% csrf_token %}
	<div style="color:red"><span id="non_field_errors" >{{ form.non_field_errors }}</span></div>

	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %}error{% endif %}">
		 <label class="control-label">{{ field.label }}</label>
		<div class="controls">
			{{ field }}
			<span class="help-inline">{{ field.errors }}</span>
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
		{{ field }}
	{% endfor %}
	
	<div class="control-group">
    	<div class="controls">
			<input type='submit' class="btn btn-success" value = "Login"/>
			<a href="{% url 'home' %}" class="btn">Back</a>
		</div>
	</div>
</form>

itblog/main/templates/main/forms/rowform.html
<script>
	$('#id_name').tooltip({
		'trigger' : 'manual'
		}
	)
</script>
<form method="POST" action="" class="row-form">
	{% for field in form.visible_fields %}
		<div class="control-group {% if field.errors %}error{% endif %} help"
			 title="{% if field.errors %}
			 			{% for error in field.errors %}
			 				{{ error }}
			 			{% endfor %}
			 		{% endif %}" style="margin:0">
			<div class="controls">
				{{ field }}
			</div>
		</div>
	{% endfor %}
	{% for field in form.hidden_fields %}
		{{ field }}
	{% endfor %}
</form>

itblog/main/templates/main/forms/searchform.html
<script>
	$(document).ready(function() {

	$('#id_search').popover({
		trigger: 'focus',
		placement : 'top',
		toggle: "popover",
		content: "Use double quotes to find exact matchings.",
		title: "Search tip",
	});


	  $(window).keydown(function(event){
	    if((event.keyCode == 13) && $('#id_search').val() == '') {
	      event.preventDefault();
	      return false;
	    }
	  });
	});


</script>
{% load extra_tags %}
<form action="{% url 'main' 'search' 0 %}" method="GET">
	<div class="input-append">
		<input class="input-medium" id="id_search" name="q" type="text" value="{{ query }}" autocomplete="off"> 
		<button type="button" class="btn" onclick="if ($('#id_search').val() != '') {this.form.submit()}">
			Search
		</button>
	</div>
</form>

itblog/main/templates/main/forms/subjectform.html
<!--form-->
<form method="POST">{% csrf_token %}
	
	<div class="control-group">
    	<div class="controls">
			<div style="color:red">{{ form.non_field_errors }}</div>
		</div>
	</div>

	{% for field in form.visible_fields %}
	<div class="control-group {% if field.errors %}error{% endif %}">
		<!-- <label class="control-label" for="inputWarning">{{ field.label }}</label> -->
		<div class="controls">
			{{ field }}
			<span class="help-inline">{{ field.errors }}</span>
		</div>
	</div>
	{% endfor %}
	
	{% for field in form.hidden_fields %}
		{{ field }}
	{% endfor %}
	
	<div class="control-group">
    	<div class="controls">
			<input type='submit' class="btn btn-success" value = "Save subject"/>
			<a href="" onclick="window.location.reload()" class="btn">Cancel</a>
		</div>
	</div>
</form>