itblog/itblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import main.views
import main.login_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main.views.home, name='home'),
    url(r'^subject$', main.views.subjects, name='subjects'),
    url(r'^about$', main.views.about, name='about'),
    url(r'^links$', main.views.links, name='links'),

    url(r'^accounts/login/$', main.login_views.login_user, name='login'),
    url(r'^login$', main.login_views.login_user, name='login'),
    url(r'^logout', main.login_views.logout_user, name='logout'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

articles = [
    url(r'^(?P<page_type>tags|subjects|search|recent)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)$', main.views.main, name='main'),
    url(r'^(?P<page_type>tags|subjects|search|recent)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)/(?P<page>\d+)/(?P<delta>\d+)$', main.views.main, name='main'),
    url(r'^blog/(?P<article_id>\d+)$', main.views.blog, name='blog'),
]

article = [
    url(r'^add$', main.views.add_article, name='addarticle'),
    url(r'^edit/(?P<article_id>\d+)$', main.views.edit_article, name='editarticle'),
    url(r'^preview/(?P<article_id>\d+)$', main.views.preview_article, name='previewarticle'),
]

comments = [
    url(r'^answer_to/(?P<comment_id>\d+)$', main.views.comment_dialog, name='commentdialog'),
    url(r'^edit/(?P<comment_id>\d+)$', main.views.edit_comment, name='editcomment'),
]

urlpatterns += [
    url(r'^articles/', include(articles)),
    url(r'^article/', include(article)),
    url(r'^comments/', include(comments)),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

itblog/tasks/urls.py
from django.conf.urls import include, url

import tasks.views


urlpatterns = [
    url(r'^(?P<page_type>tags|subjects|search|all)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)$', tasks.views.main, name='tasks'),
    url(r'^(?P<page_type>tags|subjects|search|all)/(?P<item_name>[A-Za-z0-9_\-\.&% ]+)/(?P<page>\d+)/(?P<delta>\d+)$', tasks.views.main, name='tasks'),
    url(r'^subjects$', tasks.views.subjects, name='tasksubjects'),
    url(r'^(?P<task_id>\d+)$', tasks.views.task, name='task'),
    url(r'^add$', tasks.views.add_task, name='addtask'),
    url(r'^edit/(?P<task_id>\d+)$', tasks.views.edit_task, name='edittask'),
    url(r'^solution/edit/(?P<solution_id>\d+)$', tasks.views.edit_solution, name='editsolution'),
    url(r'^comment/(?P<solution_id>\d+)$', tasks.views.add_solution_comment, name='addsolutioncomment'),
    url(r'^comment/(?P<comment_id>\d+)/edit$', tasks.views.edit_solution_comment, name='editsolutioncomment'),
]

itblog/main/models.py
from django.db import models
from django.contrib.auth.models import User

import os

def _get_upload_path(instance, filename):
    return filename
#     return os.path.join(instance.article.id, filename)


class Subject(models.Model):
    
    name = models.CharField(max_length=40, unique=True)
    parent_subject = models.ForeignKey('self', blank=True, null=True, verbose_name='Parent subject')
    
    def __unicode__(self):
        return self.name


class Tag(models.Model):
    
    name = models.CharField(max_length=30, unique=True)
    description = models.TextField(blank=True, null=True)
    creator = models.ForeignKey(User, on_delete=models.SET(None))
    amount = models.PositiveIntegerField(default=0)
    
    def __unicode__(self):
        return self.name


class Article(models.Model):
    
    author = models.ForeignKey(User, on_delete=models.SET(0))
    title = models.CharField(max_length=100, unique=True)
    body = models.TextField()
    subject = models.ForeignKey(Subject, on_delete=models.SET(0))
    date = models.DateTimeField(auto_now=True)
#     tags = models.CharField(max_length=200)
    mtags = models.ManyToManyField(Tag)
    is_published = models.BooleanField(default=False)
    
    @property
    def tags_list(self):
        return self.tags.split(',')
    
    def is_in_favorites(self, user):
        return True if Favorite.objects.filter(article_id=self.id, owner=user) else False


class ArticleImage(models.Model):
    
    article = models.ForeignKey(Article, null=True, blank=True)
    image = models.ImageField(upload_to=_get_upload_path)


class UsefulLink(models.Model):
    
    url = models.URLField(max_length=300)
    description = models.CharField(max_length=100, blank=True, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.SET(0))
    
    def __unicode__(self):
        return self.url


class Comment(models.Model):
    
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Name')
    author = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET('Undefined'))
    body = models.TextField(verbose_name='Comment')
    article = models.ForeignKey(Article)
    date = models.DateTimeField(auto_now=True)
    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='Parent comment')


class Favorite(models.Model):
    
    class Meta:
        unique_together = ('owner', 'article')
    
    owner = models.ForeignKey(User)
    comment = models.TextField(verbose_name='Comment', blank=True, null=True)
    article = models.ForeignKey(Article)

itblog/main/views.py
#coding: utf-8 
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.datastructures import MultiValueDict
from django import forms

from .forms import *
from .models import *
from .utils import get_query, get_pagination_info, \
                  send_mail, refresh_captcha, get_neighbors


import json

def home(request):
    context_dict = {}
    context_dict['recent_articles'] = get_recent_articles()
    context_dict['tags'] = Tag.objects.all().filter(article__is_published=True)\
                                .distinct().order_by('name')
    context_dict['list'] = get_subjects_tree()
    return render(request, 'main/home.html', context_dict)

@login_required
def subjects(request):
    """
    Is responsible for 'Subjects manager'
    """
    result = []
    for subject in Subject.objects.filter(parent_subject=None):
        result.append({
                'parent' : subject,
                'children' : Subject.objects.filter(parent_subject=subject)})
    
    if request.method == 'POST':
        # add subject
        if not request.POST.get('item_id'):
            form = SubjectForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('subjects')
        
        # edit subject
        elif request.POST.get('edit_request'):
            subject = Subject.objects.get(pk=int(request.POST['item_id']))
            form = SubjectForm(instance=subject)
            return render(request,
                                      'main/forms/rowform.html',
                                      {
                                       'form' : form ,
                                       'item_id' : subject.id
                                       })
        
        elif request.POST.get('edit_submit'):
            form = SubjectForm(request.POST,
                               instance=Subject.objects.get(
                                                    pk=request.POST['item_id']))
            if form.is_valid():
                form.save()
                return HttpResponse("")
            else:
                return render(request,
                                          'main/forms/rowform.html',
                                          {
                                           'form' : form ,
                                           'item_id' : request.POST['item_id']
                                           })
        
        # delete subject
        elif request.POST.get('delete_request'): 
            subject = Subject.objects.get(pk=int(request.POST['item_id']))
            subject.delete()
            return HttpResponse('')
    # empty form
    else:
        form = SubjectForm()
    return render(request, 'main/base/subjects.html',
                              {
                               'page_title' : 'Articles subjects',
                               'result' : result,
                               'form' : form
                               })


def main(request, page_type, item_name, page=1, delta=10, **kwargs):
    
    context_dict = {}
    context_dict['recent_articles'] = get_recent_articles()
    context_dict['tags'] = Tag.objects.all().filter(article__is_published=True)\
                                .distinct().order_by('name')
    context_dict['list'] = get_subjects_tree()
    context_dict['page_type'] = page_type
    context_dict['item_name'] = item_name
    
    # subjects_results, tag_results, search_results, recent_results
    return globals()[page_type + '_results'](request, context_dict,
                                             item_name=item_name,
                                             page=int(page),
                                             delta=int(delta))


def blog(request, article_id=0):
    
    context_dict = {}
    context_dict['recent_articles'] = get_recent_articles()
    context_dict['tags'] = Tag.objects.all().filter(article__is_published=True)\
                                .distinct().order_by('name')
    context_dict['list'] = get_subjects_tree()
    context_dict['query'] = request.GET.get('q', '')

    if not int(article_id):
        return redirect('main', 'recent', 0)
 
    try:
        article = Article.objects.get(pk=int(article_id), is_published=True)
        articles = list(Article.objects.filter(subject=article.subject,
                                           is_published=True).order_by('pk'))
         
        context_dict['previous'], context_dict['next'] = get_neighbors(article,
                                                                       articles)
    except Article.DoesNotExist:
        return redirect('main', 'recent', 0)

    context_dict['article'] = article
        
    if request.user.is_authenticated():
        form = CommentForm(initial={'author': request.user,
                                    'article':article,
                                    'parent_comment' : None})
        form.fields['name'].widget = forms.HiddenInput()
    else:
        form = CommentForm(initial={'article':article,
                                    'parent_comment' : None})
     
    if request.is_ajax() and 'refresh_captcha' in request.GET:
        return refresh_captcha()
     
    if request.method == 'POST':
        if request.POST.get('add_request'):
            if request.POST['type'] == 'favorites':
                Favorite.objects.create(owner=request.user, article=article)
        if request.POST.get('delete_request'):
            if request.POST['type'] == 'comment':
                comment = Comment.objects.get(pk=int(request.POST['item_id']))
                comment.delete()
            elif request.POST['type'] == 'article':
                article = Article.objects.get(pk=int(request.POST['item_id']))
                 
                for tag in article.mtags.all():
                    tag.amount -= 1
                    tag.save()
                 
                for img in ArticleImage.objects.filter(article=article):
                    _delete_image(img.id)
                 
                article.delete()
                return HttpResponse('Article was successfully deleted.')
            elif request.POST['type'] == 'favorite':
                favorite = Favorite.objects.get(article_id=article_id)
                favorite.delete()
        else:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save()
                 
                message_subject = 'New comment for your article \"%s\"' \
                                                                % article.title
                message_body = "User %s has added a new comment to your post." +\
                "\nGo here and view it:\nwww.it-recipes.com%s" 
                message_body = message_body % (comment.author, request.get_full_path())
                 
                send_mail(article.author.email, message_subject, message_body)
                 
                return redirect('blog', article.id)
            else:
                if request.user.is_authenticated():
                    form.fields['name'].widget = forms.HiddenInput()
     
    context_dict['form'] = form
    context_dict['comments'] = get_comments_tree(article_id)
    
    return render(request, 'main/blog/blog.html', context_dict)


def edit_comment(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    form = CommentForm(instance=comment)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('blog', comment.article.id)
    if request.user.is_authenticated():
        form.fields['name'].widget = forms.HiddenInput()
    return render(request, 'main/blog/editcomment.html',
                    {
                     'comment' : comment,
                     'form' : form,
                     'cancel_link' : reverse('blog', args=(comment.article.id,))
                     })


def comment_dialog(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    if request.user.is_authenticated():
        form = CommentForm(initial={'author': request.user,
                                    'article':comment.article,
                                    'parent_comment' : comment})
    else:
        form = CommentForm(initial={'article':comment.article,
                                    'parent_comment' : comment})
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog', comment.article.id)
    if request.user.is_authenticated():
        form.fields['name'].widget = forms.HiddenInput()
    return render(request, 'main/blog/commentdialog.html',
                    {
                     'comment_dialog' : get_comment_dialog(comment_id),
                     'form' : form,
                     'cancel_link' : reverse('blog', args=(comment.article.id,))
                     })


def tags_results(request, context_dict, **kwargs):
    tag_name = str(kwargs.get('item_name'))
    p = int(kwargs.get('page'))
    delta = int(kwargs.get('delta'))
    try:
        articles = Tag.objects.get(name=tag_name).article_set\
                                                    .filter(is_published=True)\
                                                    .select_related('subject')
    except Tag.DoesNotExist:
        articles = []
                                                

itblog/main/templates/main/base/about.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}
	<div class="row">
		<div class="span2">
			<div class="circular"><img src="{% static "img/avatars/ochirkov.jpg" %}" alt="" /></div>
		</div>
		<div class="span10">
			<h3>Oleksandr Chirkov</h3>
			<img class="logo" src="{% static "img/logos/linkedin.png" %}"/><b>&nbsp;LinkedIn: </b><a href="http://www.linkedin.com/pub/oleksandr-chirkov/5a/87/80b/" %}">http://www.linkedin.com/pub/oleksandr-chirkov/5a/87/80b/</a><br/>
			<img class="logo" src="{% static "img/logos/vk.png" %}"/><b>&nbsp;VK: </b><a href="http://vk.com/id90745379">http://vk.com/id90745379</a><br/>
			<img class="logo" src="{% static "img/logos/skype.png" %}"/><b>&nbsp;Skype: </b>loriin14<br/>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<hr align="center" size="2" color="#ff0000" />
		</div>
	</div>
	<div class="row">
		<div class="span2">
			<div class="circular"><img src="{% static "img/avatars/AnaPana.jpg" %}" alt="" /></div>
		</div>
		<div class="span10">
			<h3>Anastasia Panchenko</h3>
				Hello everyone! Wellcome to our blog.<br/>
				I am very interested in Python language and also in web development, especially on Django.<br/>
				Here I store some things I faced with.<br/>
				If you have any suggestions, you can leave a comment or contact me by following links:<br/><br/>
				<img class="logo" src="{% static "img/logos/linkedin.png" %}"/><b>&nbsp;LinkedIn: </b><a href="http://www.linkedin.com/pub/anastasia-panchenko/30/894/234/">http://www.linkedin.com/pub/anastasia-panchenko/30/894/234</a><br/>
				<img class="logo" src="{% static "img/logos/fb.png" %}"/><b>&nbsp;Facebook: </b><a href="https://www.facebook.com/ana.pana.31">https://www.facebook.com/ana.pana.31</a><br/>
				<img class="logo" src="{% static "img/logos/skype.png" %}"/><b>&nbsp;Skype: </b>nastyarpd<br/>
				<img class="logo" src="{% static "img/logos/google.png" %}"/><b>&nbsp;Gmail: </b>ana.pana.2701 [at] gmail [dot] com<br/>
		</div>
	</div>
{% endblock %}

itblog/main/templates/main/base/links.html
{% extends 'main/base.html' %}

{% block content %}
<script>
	function remove_item(event, id) {
		(event.preventDefault) ? event.preventDefault() : event.returnValue = false;
		var r = confirm("Do you really want to remove subject?");
		if (r == true) {
			$.post("{{ request.get_full_path }}", {
				delete_request : 1,
				item_id : id,
				csrfmiddlewaretoken : getCookie('csrftoken')
			}, function(data) {
				window.location.reload();
			});
		}
	}
</script>

<div class="row">
	<div class="span8">
		{% if list %}
			{% for item in list %}
			<div class="subjects-list">
				<h4>{{ item.subject.name }}</h4>
				<table class="table">
					{% for link in item.links %}
					<tr>
						<td>
						<p>
							<a href="{{ link.url }}">{{ link.url|slice:":50" }} {% if link.url|length > 50 %}...{% endif %}</a> &nbsp;-&nbsp; <span class="muted">{{ link.description }}</span></td>
						</p>
						{% if user.is_authenticated %}
							<td width="100" height="30">
								<div class="pull-right">
									<a class="btn btn-mini row-btn" onclick="remove_item(event, '{{ link.id }}');" href=""><i class="icon-remove"></i></a>
								</div>
							</td>
						{% endif %}
					</tr>
					{% endfor %}
				</table>
			</div>
			{% endfor %}
		{% endif %}
	</div>
	<div class="span1"></div>
	<div class="span3">
		{% include 'main/forms/searchform.html' %}
		<br/>
		<br/>
		{% if user.is_authenticated %}
			<h4>Add link</h4>
			{% include 'main/forms/defaultform.html' %}
		{% endif %}
	</div>
</div>
{% endblock %}

itblog/main/templates/main/base/login.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>IT Blog</title>

		<link href="{% static "css/main.css" %}" rel="stylesheet" media="screen">
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
		<link href="{% static "css/bootstrap-tagmanager.css" %}" rel="stylesheet" media="screen">
		<link href="{% static "css/jquery-ui.css" %}" rel="stylesheet" />
		<link href="{% static "js/ckeditor/contents.css" %}" rel="stylesheet" />
		<script type="text/javascript" src="{% static "js/jquery-1.9.1.min.js" %}" ></script>
		<script type="text/javascript" src="{% static "js/jquery-ui-1.9.2.custom.min.js" %}" ></script>
		<script type="text/javascript" src="{% static "js/django-coockies.js" %}" ></script>
		<script src="{% static "js/bootstrap.min.js" %}"></script>
		<script src="{% static "js/ckeditor/ckeditor.js" %}"></script>
	</head>
	<body class="body">
		<div class="container">
			<div class="row">
				<div style="margin-left: 150px; margin-top: 150px;">
					{% include 'main/forms/loginform.html' %}
				</div>
			</div>
		</div>
	</body>
</html>

itblog/main/templates/main/base/pagination.html
{% if articles and pagination.range_step < pagination.lst_len %}
	<script type="text/javascript">
	
	function change_delta(delta) {
		if (delta == 'All') {
			delta = '{{ pagination.lst_len }}'
		}
		window.location.href = '/articles/{{ page_type }}/{{ item_name }}/1/' + delta + '{% if query %}?q={{ query }}{% endif %}';
	};
	
	</script>
	
	<div class="pagination">
		<select id="select_range" name="delta" class="pagin_range input-mini" onchange="change_delta($('#select_range').find(':selected').val())" >
			{% for range in pagination.delta_range %}
				<option value="{{ range }}" {% if range == pagination.delta %}selected="selected"{% endif %}>{{ range }}</option>
			{% endfor %}
			<option value="All" {% if pagination.all %}selected="selected"{% endif %}>All</option>
		</select>
		<ul style="float:left;">{% with current=pagination.p %}
			<li class="{% if current == pagination.page_range|first %}disabled{% endif %}">
				<a {% if not current == pagination.page_range|first %}href="{% url 'main' page_type item_name current|add:'-1' pagination.delta %}{% if query %}?q={{ query }}{% endif %}" {% endif %} >«</a>
			</li>
			
			{% for page in pagination.page_range %}
				{% if current < page|add:'3' and current > page|add:'-3' or forloop.first or forloop.last %}
					<li class="{% if current == page %}active{% endif %}">
							<a {% if not current == page %}href = "{% url 'main' page_type item_name page pagination.delta %}{% if query %}?q={{ query }}{% endif %}"{% endif %}>
								{{ page }}
							</a>
					</li>
				{% elif current == page|add:'3' or current == page|add:'-3' %}
					<li class="disabled">
							<span>...</span>
					</li>
				{% endif %}
			{% endfor %}
			<li class="{% if current == pagination.page_range|last %}disabled{% endif %}">
				<a {% if not current == pagination.page_range|last %}href="{% url 'main' page_type item_name current|add:'1' pagination.delta %}{% if query %}?q={{ query }}{% endif %}"{% endif %}">»</a>
			</li>
			{% endwith %}
		</ul>
	</div>
{% endif %}

itblog/main/templates/main/base/subjects.html
{% extends 'main/base.html' %}
{% block content %}
<script>
function edit_item(event, id) {
    
    (event.preventDefault) ? event.preventDefault() : event.returnValue = false;
	$.post("{{ request.get_full_path }}", {
		edit_request : 1,
		item_id : id,
		csrfmiddlewaretoken: getCookie('csrftoken')
	},
	function(data) {
		$("#subject_name_" + id).html(data);
		// $("#id_parent_subject").addClass('hidden');
		$("div[id^='menu_buttons_']").addClass('hidden');
		$("#edit_buttons_" + id).removeClass('hidden');
	});
}

function submit_item(event, id) {
    
    (event.preventDefault) ? event.preventDefault() : event.returnValue = false;
	$.post("{{ request.get_full_path }}", {
		edit_submit : 1,
		item_id : id,
		name: $('#id_name').val(),
		author : $('#id_author').val(),
		parent_subject : $('#id_parent_subject').val(),
		csrfmiddlewaretoken: getCookie('csrftoken')
	},
	function(data) {
		if (data == "") {
			window.location.reload();
		}
		else {
			$("#subject_name_" + id).html(data);
			$('.control-group.error').tooltip({
				'trigger' : 'manual'
				}
			)
			$('.control-group.error').tooltip('show');
		}
	});
}

</script>
<div class="row">
	<div class="span7">
		<h4>{{ page_title }}</h4>
		{% if result %}
			<table class="table">
				{% for item in result %}
					<tr>
						<td><div id="subject_name_{{ item.parent.id }}"><strong>{{ item.parent.name }}</strong></div></td>
	
						<td width="150" height="30">
							<div id="menu_buttons_{{ item.parent.id }}" class="pull-right">
								<a class="btn btn-mini row-btn" onclick="edit_item(event, '{{ item.parent.id }}');" href=""><i class="icon-edit"></i> Edit</a>
								<a class="btn btn-mini row-btn" onclick="remove_item(event, '{{ item.parent.id }}', 'subject');" href=""><i class="icon-remove"></i> Remove</a>
							</div>
							<div id="edit_buttons_{{ item.parent.id }}" class="hidden pull-right">
								<a class="btn btn-mini btn-success row-btn" href="" onclick="submit_item(event, '{{ item.parent.id }}')">Save</a>
								<a class="btn btn-mini row-btn" href="" onclick="window.location.reload();">Cancel</a>
							</div>
						</td>
						
					</tr>
					{% if item.children %}
						{% for subj in item.children %}
							<tr>
								<td>
									<div id="subject_name_{{ subj.id }}" style="margin-left:30px;">{{ subj.name }}</div>
								</td>
								
								<td width="150" height="30">
									<div id="menu_buttons_{{ subj.id }}" class="pull-right">
										<a class="btn btn-mini row-btn" onclick="edit_item(event, '{{ subj.id }}');" href=""><i class="icon-edit"></i> Edit</a>
										<a class="btn btn-mini row-btn" onclick="remove_item(event, '{{ subj.id }}', 'subject');" href=""><i class="icon-remove"></i> Remove</a>
									</div>
									<div id="edit_buttons_{{ subj.id }}" class="hidden pull-right">
										<a class="btn btn-mini btn-success row-btn" href="" onclick="submit_item(event, '{{ subj.id }}')">Save</a>
										<a class="btn btn-mini row-btn" href="" onclick="window.location.reload();">Cancel</a>
									</div>
								</td>

							</tr>
						{% endfor %}
					{% endif %}
				{% endfor %}
			</table>
		{% endif %}
	</div>
	<div class="span1">
	</div>
	<div class="span4">
		<h4>Add subject</h4>
		{% include 'main/forms/subjectform.html' %}
	</div>
</div>
{% endblock %}